"""initial schema

Revision ID: 071d5ae930fc
Revises: 
Create Date: 2026-07-27 00:18:55.943174

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '071d5ae930fc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('software_inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.Enum('production', 'staging', 'development', 'unknown', name='asset_environment', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before_ref', sa.String(length=1024), nullable=True),
    sa.Column('after_ref', sa.String(length=1024), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('analyst', 'senior_analyst', 'manager', 'admin', 'auditor', name='user_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='user_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('sso_subject', name=op.f('uq_users_sso_subject'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('investigations',
    sa.Column('trigger_source', sa.Enum('analyst', 'alert', 'scheduled', name='trigger_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'awaiting_approval', 'closed', 'archived', name='investigation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_investigations_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index(op.f('ix_investigations_owner_id'), 'investigations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_index('ix_investigations_status_severity', 'investigations', ['status', 'severity'], unique=False)
    op.create_table('conversations',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_conversations_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_investigation_id'), 'conversations', ['investigation_id'], unique=False)
    op.create_table('cve_findings',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('cvss', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('applicability', sa.Enum('confirmed', 'candidate', 'not_applicable', name='cve_applicability', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('exploit_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_freshness', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_cve_findings_asset_id_assets')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_cve_findings_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cve_findings'))
    )
    op.create_index(op.f('ix_cve_findings_asset_id'), 'cve_findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_cve_findings_cve_id'), 'cve_findings', ['cve_id'], unique=False)
    op.create_index(op.f('ix_cve_findings_investigation_id'), 'cve_findings', ['investigation_id'], unique=False)
    op.create_table('log_events',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('raw_ref', sa.String(length=1024), nullable=True),
    sa.Column('notability', sa.Float(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_log_events_asset_id_assets')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_log_events_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_events'))
    )
    op.create_index(op.f('ix_log_events_asset_id'), 'log_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_log_events_event_type'), 'log_events', ['event_type'], unique=False)
    op.create_index('ix_log_events_investigation_event_time', 'log_events', ['investigation_id', 'event_time'], unique=False)
    op.create_index(op.f('ix_log_events_investigation_id'), 'log_events', ['investigation_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('patch', 'configuration', 'mitigation', 'other', name='recommendation_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='triage_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('expected_impact', sa.String(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', 'edited', name='approval_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_recommendations_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_approval_status'), 'recommendations', ['approval_status'], unique=False)
    op.create_index(op.f('ix_recommendations_investigation_id'), 'recommendations', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    op.create_table('reports',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('executive_summary', sa.String(), nullable=False),
    sa.Column('technical_body', sa.String(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'final', name='report_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_reports_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('investigation_id', 'version', name='uq_reports_investigation_version')
    )
    op.create_index(op.f('ix_reports_investigation_id'), 'reports', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('threat_assessments',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.Enum('benign', 'suspicious', 'malicious', name='verdict', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('triage_priority', sa.Enum('low', 'medium', 'high', 'urgent', name='triage_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('enrichment_status', sa.Enum('complete', 'degraded', 'unavailable', name='enrichment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('iocs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attack_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_threat_assessments_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_assessments'))
    )
    op.create_index(op.f('ix_threat_assessments_investigation_id'), 'threat_assessments', ['investigation_id'], unique=False)
    op.create_table('human_decisions',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'edit', 'reject', 'redirect', name='decision_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_human_decisions_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_human_decisions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_decisions'))
    )
    op.create_index(op.f('ix_human_decisions_conversation_id'), 'human_decisions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_human_decisions_user_id'), 'human_decisions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('author_type', sa.Enum('human', 'system', 'agent', name='message_author_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('notifications',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('slack', 'email', 'webhook', name='notification_channel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('payload_ref', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'dead_letter', name='notification_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['human_decisions.id'], name=op.f('fk_notifications_approval_id_human_decisions')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_notifications_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_investigation_id'), 'notifications', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_investigation_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_human_decisions_user_id'), table_name='human_decisions')
    op.drop_index(op.f('ix_human_decisions_conversation_id'), table_name='human_decisions')
    op.drop_table('human_decisions')
    op.drop_index(op.f('ix_threat_assessments_investigation_id'), table_name='threat_assessments')
    op.drop_table('threat_assessments')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_investigation_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_investigation_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_approval_status'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_log_events_investigation_id'), table_name='log_events')
    op.drop_index('ix_log_events_investigation_event_time', table_name='log_events')
    op.drop_index(op.f('ix_log_events_event_type'), table_name='log_events')
    op.drop_index(op.f('ix_log_events_asset_id'), table_name='log_events')
    op.drop_table('log_events')
    op.drop_index(op.f('ix_cve_findings_investigation_id'), table_name='cve_findings')
    op.drop_index(op.f('ix_cve_findings_cve_id'), table_name='cve_findings')
    op.drop_index(op.f('ix_cve_findings_asset_id'), table_name='cve_findings')
    op.drop_table('cve_findings')
    op.drop_index(op.f('ix_conversations_investigation_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_investigations_status_severity', table_name='investigations')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_owner_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
