"""memory layer tables

Revision ID: 7fb8de9fa709
Revises: 071d5ae930fc
Create Date: 2026-08-01 12:34:06.211729

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fb8de9fa709'
down_revision: str | None = '071d5ae930fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_memory_index',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('asset', 'ioc', 'technique', 'cve', name='memory_index_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_memory_index_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_memory_index')),
    sa.UniqueConstraint('investigation_id', 'kind', 'value', name='uq_investigation_memory_index_investigation_kind_value')
    )
    op.create_index(op.f('ix_investigation_memory_index_investigation_id'), 'investigation_memory_index', ['investigation_id'], unique=False)
    op.create_index('ix_investigation_memory_index_kind_value', 'investigation_memory_index', ['kind', 'value'], unique=False)
    op.create_table('session_memory_entries',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_session_memory_entries_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_memory_entries')),
    sa.UniqueConstraint('investigation_id', 'key', 'revision', name='uq_session_memory_entries_investigation_key_revision')
    )
    op.create_index(op.f('ix_session_memory_entries_investigation_id'), 'session_memory_entries', ['investigation_id'], unique=False)
    op.create_index('ix_session_memory_entries_investigation_key', 'session_memory_entries', ['investigation_id', 'key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_memory_entries_investigation_key', table_name='session_memory_entries')
    op.drop_index(op.f('ix_session_memory_entries_investigation_id'), table_name='session_memory_entries')
    op.drop_table('session_memory_entries')
    op.drop_index('ix_investigation_memory_index_kind_value', table_name='investigation_memory_index')
    op.drop_index(op.f('ix_investigation_memory_index_investigation_id'), table_name='investigation_memory_index')
    op.drop_table('investigation_memory_index')
    # ### end Alembic commands ###
