"""knowledge index for rag

Revision ID: 9521f5e77c49
Revises: 7fb8de9fa709
Create Date: 2026-08-01 13:03:22.607430

"""

from collections.abc import Sequence

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9521f5e77c49'
down_revision: str | None = '7fb8de9fa709'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The knowledge index stores embeddings, so the pgvector extension must exist
    # before the table that uses its type. Creating it here keeps the migration
    # self-contained rather than relying on the database being pre-provisioned.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('chunk_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('source_kind', sa.Enum('nvd', 'mitre_attack', 'advisory', 'internal_runbook', name='knowledge_source_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('trust_tier', sa.Enum('authoritative', 'vendor', 'community', 'internal', name='source_trust_tier', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_version', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('cwe_id', sa.String(length=32), nullable=True),
    sa.Column('technique_id', sa.String(length=32), nullable=True),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('parent_chunk_id', sa.String(length=255), nullable=True),
    sa.Column('index_version', sa.String(length=128), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks')),
    sa.UniqueConstraint('chunk_id', 'index_version', name='uq_knowledge_chunks_chunk_id_index_version')
    )
    op.create_index('ix_knowledge_chunks_cve_id', 'knowledge_chunks', ['cve_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index('ix_knowledge_chunks_retired_at', 'knowledge_chunks', ['retired_at'], unique=False)
    op.create_index('ix_knowledge_chunks_source_version', 'knowledge_chunks', ['source_id', 'index_version'], unique=False)
    op.create_index('ix_knowledge_chunks_technique_id', 'knowledge_chunks', ['technique_id'], unique=False)
    op.create_table('knowledge_index_versions',
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('building', 'active', 'retired', name='index_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_index_versions')),
    sa.UniqueConstraint('source_id', 'version', name='uq_knowledge_index_versions_source_id_version')
    )
    op.create_index('ix_knowledge_index_versions_source_status', 'knowledge_index_versions', ['source_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_index_versions_source_status', table_name='knowledge_index_versions')
    op.drop_table('knowledge_index_versions')
    op.drop_index('ix_knowledge_chunks_technique_id', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_source_version', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_retired_at', table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_cve_id', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
